### ISSUE TITLE
Your extension not working

### ISSUE THREAD

**Issue by thienha1** [CENSUS/ghidra-frida-hook-gen#1]
I dunno why it not work for me, follow as your instruction, then active extension and restart Ghidra, after analysis file and when i press right click on function i need like:
![Hook_demo](https://user-images.githubusercontent.com/18132856/215242068-ba99f43d-cdfa-4f52-901b-30363d5e7be8.png)
Also has been wait more than 5s and still not appear

**Comment by CarrotCultivator** [comment]
I had the same problem sometime ago, but it seems that Ghidra requires the plugin folder to be named as the name of the plugin itself. In other words, the folder that comes out of the .zip file should not be renamed. 
It may be that this is the reason why you don't see the options.

**Comment by thienha1** [comment]
> I had the same problem sometime ago, but it seems that Ghidra requires the plugin folder to be named as the name of the plugin itself. In other words, the folder that comes out of the .zip file should not be renamed. It may be that this is the reason why you don't see the options.

I'm not rename folder and just modify extVersion in extension.properties like
![Capture](https://user-images.githubusercontent.com/18132856/215972310-26cbf6a3-4891-4066-8474-97d0ab1903e9.PNG)
![Capture](https://user-images.githubusercontent.com/18132856/215972529-10a1760c-bbef-4394-bc5e-dc7bc3b63363.PNG)
Then add this extension
![Capture](https://user-images.githubusercontent.com/18132856/215972806-276d454b-306d-4c62-aa82-79cc7e01f275.PNG)
![Capture](https://user-images.githubusercontent.com/18132856/215972954-62929c54-9e77-4038-95ec-72988bcd80dd.PNG)
And restart Ghidra to take effect but reality see nothing change after that.. Still not appear after all steps

**Comment by CarrotCultivator** [comment]
Do not download the repository as a whole, you don't need to unless you want to build the code. Download the latest version from https://github.com/CENSUS/ghidra-frida-hook-gen/tree/main/dist , and don't change the folder name when decompressing (leave it as-is as it comes from the .zip file). Also make sure that the "version" line in the "extension.properties" file (after decompressing) is your Ghidra version (in your case, 10.2.2) . You don't need to change the line with the "name".

**Comment by thienha1** [comment]
> Do not download the repository as a whole, you don't need to unless you want to build the code. Download the latest version from https://github.com/CENSUS/ghidra-frida-hook-gen/tree/main/dist , and don't change the folder name when decompressing (leave it as-is as it comes from the .zip file). Also make sure that the "version" line in the "extension.properties" file (after decompressing) is your Ghidra version (in your case, 10.2.2) . You don't need to change the line with the "name".

I tried to follow your instruction and now it works, thanks for your kind!!!
